console.clear();

console.log("\n");

// Import the CommonJS bundle generated by Rollup
const ObjectDataValidator = require('./dist/bundle.cjs.js');

const data = {

   hasChildrenUnder16 : 'Yes',
   numChildrenUnder16 : 10,
   
};

// Generate a regex rule for alpha numeric characters only

const regex = "^(?=.*[a-zA-Z])(?=.*[0-9])[A-Za-z0-9]+$";

const rules = [
    {
        field_name: 'hasChildrenUnder16',
        field_label: 'Has children under 16',
        rules: [
            {
                name: 'required',
                message: 'Please specify if you have children under 16'
            },
        ]

    },
   {
      field_name: 'numChildrenUnder16',
      field_label: 'Number of children under 16',
      rules: [
         {
            name : 'required_if_target_equals',
            data :  {
               target_field : 'hasChildrenUnder16',
               value : 'Yes'
            },
            message: 'Please specify the number of children under 16'
         },
         {
            name: 'integer',
            message: 'Number of children under 16 must be an integer'
         },
         {
            name: 'lesser',
            data: {
               target: 10
            }
         }
      ]
   }
];

// Create an instance of your class
const instance = new ObjectDataValidator({
    data: data,
    rules: rules
});

// Call a method on the instance to test it
console.log(instance.validate());

console.log("\n");