console.clear();

console.log("\n");

// Import the CommonJS bundle generated by Rollup
const ObjectDataValidator = require('./dist/bundle.cjs.min.js');

const data = require('./test-data/data_temp.json');

const rules = require('./test-data/rules_temp.json');


// Create an instance of your class
const instance = new ObjectDataValidator({
    data: data,
    rules: rules
});

// Call a method on the instance to test it
console.log(instance.validate());

console.log("\n");