// Import the CommonJS bundle generated by Rollup
const ObjectDataValidator = require('./dist/bundle.cjs.js');

// Create an instance of your class
const instance = new ObjectDataValidator({
    data : {name : 'Anjan'},
    rules : [
        {
            field_name : 'name',
            field_label : 'Name',
            rules : [
                'required'
            ]
        }
    ]
});

// Call a method on the instance to test it
instance.hello();